version: '3.8'
services:
  postgres_db:
    image: timescale/timescaledb-ha:pg16
#    restart: always
    environment:
      - POSTGRES_USER=pgadmin
      - POSTGRES_PASSWORD=pw
      - POSTGRES_DB=db
    ports:
      - '5432:5432'
    volumes: 
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
    driver: local